
# node-graphql/docker-compose.yml

version: '3.8'
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
      - "4000:4000"
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules


  db:
    image: postgres
    restart: always
    healthcheck:
      test: [“CMD-SHELL”, “pg_isready”]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080